name: test
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - main

  # run tests for all pull requests
  pull_request:

jobs:
  buildnpush:
    name: Build and Push Docker Package
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GH_USERNAME: ${{ github.actor }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -f bedev.dockerfile -t devstack .

      - name: Tag and push to GitHub Container Registry
        run: |
          docker login -u $GH_USERNAME -p $GH_TOKEN ghcr.io/netapp/restic
          docker tag devstack:latest ghcr.io/theotw/devstack:latest
          docker push ghcr.io/theotw/devstack:latest

